### ISSUE TITLE
setKey throwing error

### ISSUE THREAD

**Issue by paulrobertpine** [martijnversluis/ChordSheetJS#550]
Hello, 

When I try to call setKey on my Song, I get this error:

`Error in function $21a34a464e7bc609$export$595e981f61839426 in ./node_modules/chordsheetjs/lib/index.js:1997

Cannot read properties of null (reading 'match')

./node_modules/chordsheetjs/lib/index.js:1997

  1995 | function $21a34a464e7bc609$export$595e981f61839426(string, constructor, regexes) {
  1996 |     for(let i = 0, count = regexes.length; i < count; i += 1){
> 1997 |         const match = string.match(regexes[i]);
  1998 |         if (match) return new constructor(match.groups);
  1999 |     }
  2000 |     return null`

**Comment by martijnversluis** [comment]
Hey @paulrobertpine. Could you post the song you were trying to change and the ChordSheetJS version you’re using?

**Comment by paulrobertpine** [comment]
Hi there, 

"chordsheetjs": "^6.2.2"

It happen with any of the songs in my app. Code is here: https://github.com/paulrobertpine/songbook-2022

When I tested I changed the name of the local setKey function to make sure that wasn't the issue, seen here: 

https://github.com/paulrobertpine/songbook-2022/blob/main/src/pages/%7BMarkdownRemark.fields__slug%7D.js

**Comment by martijnversluis** [comment]
Hey @paulrobertpine. I was able to figure out what happens. `setKey` _used to_ also transpose all chords. However, in your app the song key is not expressed in chordpro. This caused ChordSheetJS to try to calculate the transpose distance between `null` and the new key, which obviously will fail.

I published version `7.0.0` which addresses the issues:

- `Song#setKey` now only sets the current song key, by updating `metadata` and by inserting the key directive or updating an existing one
- `Song#changeKey` also transposes all chords.

In your app, you could either:
- specify the song key in chordpro (`{key: C}`)
- set the song key from what is specified in the frontmatter, like this: `song.setKey(frontmatterKey).changeKey(newKey)`

Please let me know if this is helpful.

**Comment by paulrobertpine** [comment]
Thanks for working on this. Well this no longer causes errors, I'm not sure it's working correctly. If I call setKey('C') on a Song, it does not set the key. I can still see currentKey: null in the code. Then this causes an error when I try to cal changeKey. 

Not all the songs are in chordPro format.

**Comment by martijnversluis** [comment]
@paulrobertpine One important detail which might cause your issue, is that `Song` is immutable. You probably need to keep the song in state:

```js
// Save the song _with_ the correct key in state
const [song, setSong] = useState(parser.parse(rawMarkdownBody).setKey(songKey));

function goDown() {
  setKey(key.transposeDown())
  song.changeKey(key);
}

function goUp() {
  setKey(key.transposeDown())
  song.changeKey(key);
}
```

**Comment by martijnversluis** [comment]
@paulrobertpine Additionally, I took some time to implement transposing on `Song`. So now you can simplify to:

```js
// Save the song _with_ the correct key in state
const [song, setSong] = useState(parser.parse(rawMarkdownBody).setKey(songKey));

function goDown() {
  setSong(song.transposeDown());
}

function goUp() {
  setSong(song.transposeDown());
}
```

**Comment by paulrobertpine** [comment]
Actually my Song was already a state variable and this line:

// Save the song _with_ the correct key in state
const [song, setSong] = useState(parser.parse(rawMarkdownBody).setKey(songKey));

Doesn't seem to fix the issue. I still have currentKey = null in the object. setKey is being fed a string.

**Comment by paulrobertpine** [comment]
Hi there, 

I can see that the key is being set in the metadata. It's the fact that the Song object contains both currentKey and transposeKey properties that threw me off.

**Comment by paulrobertpine** [comment]
One thing that is new is that the chords are being "normalized" in a way that does not always work. For example this chord "Asus2" gets changed to "A2" on transpose. Most musicians would know this chord as "Asus2".

**Comment by paulrobertpine** [comment]
Another thing is the key, stored in the metadata, does not keep minor when you transpose (e.g., Am becomes Bb (major)) on transposeUp)

**Comment by martijnversluis** [comment]
Thanks for reporting this! I added two issues to the board: #569 and #570
